---
title: "Ágio do Bezerro"
description: "O ágio do bezerro é um indicador valioso que orienta os produtores na tomada de decisões embasadas, contribuindo para operações mais rentáveis e sustentáveis no agronegócio."
author script: 
  - name: "Ítalo Marques-Monteiro"
    github: https://github.com/italomarquesmonteiro
    kaggle: https://www.kaggle.com/talomarquesmonteiro
    linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    lattes: http://lattes.cnpq.br/7174985368517137
    orcid_id: https://orcid.org/0000-0003-4367-1034
    affiliation: Smart Data
        
date: "2024-01-23"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
boi_ctpec  <- readr::read_csv("c:\\Users\\italo\\Desktop\\GitHub\\CTPec\\.vscode\\Dataset\\Cotações.csv") |>
  dplyr::filter(data <= "2021-01-25" & unidade =="kg" & produto == "Boi gordo") |>
  dplyr::select(data, produto, valor) |>
  tidyr::pivot_wider(names_from = produto, values_from = valor) |>
  dplyr::rename(boi = `Boi gordo`)

bezerro_ctpec  <- readr::read_csv("c:\\Users\\italo\\Desktop\\GitHub\\CTPec\\.vscode\\Dataset\\Cotações.csv") |>
  dplyr::filter(data <= "2021-01-25" & unidade =="kg" & produto == "Terneiro") |>
  dplyr::select(data, produto, valor) |>
  tidyr::pivot_wider(names_from = produto, values_from = valor) |>
  dplyr::rename(bezerro = Terneiro)

boi_rs <- readr::read_csv("c:/Users/italo/Desktop/GitHub/NESPro/.vscode/Dataset/GadoGordo.csv") |>
  dplyr::filter(data >= "2021-01-25" & preco == "Médio") |>
  dplyr::select(data, boi = pv_macho)

bezerro_rs <- readr::read_csv("c:/Users/italo/Desktop/GitHub/NESPro/.vscode/Dataset/GadoReposição.csv") |>
  dplyr::filter(preco == "Médio") |>
  dplyr::select(data, bezerro = terneiro_6_12_m) 
```

```{r}
boi_cptec_rs <- boi_ctpec |>
  dplyr::full_join(boi_rs) 

bezerro_cptec_rs <- bezerro_ctpec |>
  dplyr::full_join(bezerro_rs)

agio <- bezerro_cptec_rs |>
  dplyr::inner_join(boi_cptec_rs)

```

A fórmula básica para calcular o ágio do bezerro é:
  **Ágio do Bezerrro** = *{[(Preço do bezerro - Preço do boi) / Preço do boi] * 100}*

```{r}
agio_do_bezerro <- agio  |>
  dplyr::mutate(
    agio = (((bezerro - boi) / boi) * 100),
      media_movel_agio = zoo::rollmean(
        agio,
          k = 30,
            fill = NA,
              na.rm = TRUE
      )
  ) |>
  #tidyr::pivot_longer(
  #  !c(data, preco, agio),
  #    names_to = "category",
  #      values_to = "value"
  #) |>
  print(n = 20)
```

```{r}
agio_do_bezerro |>
  dplyr::mutate(media_periodo_agio = mean(agio, na.rm = TRUE))
```

media do periodo 
2024-01-31: 14.5
2024-03-13: 14.8
2024-04-03: 14.9
2024-04-25: 15.0
2024-05-16: 14.9

```{r}
bg <- "white"
txt_col <- "black"

font <- "Josefin Sans"
font2 <- "Open Sans"

# Use the font_add_google() function to load fonts from the web
sysfonts::font_add_google(family = font, font, db_cache = FALSE)
sysfonts::font_add_google(family = font2, font2, db_cache = FALSE)

sysfonts::font_add(family = "Font Awesome 6 Brands", regular = "C:/Users/italo/AppData/Local/Microsoft/Windows/Fonts/Font Awesome 6 Brands-Regular-400.otf") # nolint

#theme_set(theme_minimal(base_family = font2, base_size = 3))

showtext::showtext_opts(dpi = 300)
showtext::showtext_auto(enable = TRUE)


github_icon <- "&#xf09b"
linkedin_icon <- "&#xf0e1"
x_icon <- "&#xf099"
instagram_icon <- "&#xf16d"
github_username <- "italomarquesmonteiro"
linkedin_username <- "italomarquesmonteiro"
x_username <- "italommonteiro"
instagram_username <- "italo.m.m"

colors <- "gray40"
title_text <- glue::glue('Ágio do bezerro') 
subtitle_text <- glue::glue("Comportamento do ágio do bezerro no Rio Grande do Sul")
caption_text <- glue::glue(
  "**Dados:** Núcleo de Estudos em Sistemas de Produção de Bovinos de Corte e Cadeia Produtiva (NESPro) e Centro de Tecnologia em Pecuária (CTPEC)<br>", # nolint
  "**Nota:** Linha tracejada cinza representa o valor médios do período<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: black;'>{github_icon};</span> 
  <span style='color: black'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: dodgerblue4;'>{linkedin_icon};</span> 
  <span style='color: black'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: black'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: red;'>{instagram_icon};</span>
  <span style='color: black'>{instagram_username}</span>"
)
```

'Comportamento do <span style="color:{}">**ágio do bezerro**;</span> no Rio Grande do Sul'
```{r}
agio <- agio_do_bezerro |>
  ggplot(aes(x = data, y = agio)) +
    #geom_line(aes(y = agio), color = "grey40", size = 1.5) +
    geom_smooth(method = "gam") +
    geom_hline(yintercept = 30, lty = 1, color = "red") +
    geom_hline(yintercept = 14.2, lty = 3, color = "grey20") +
    scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
    scale_y_continuous(breaks = seq(0, 40, 5), labels = scales::dollar_format(
    prefix = "", suffix = "%")) +
  labs(
    title = title_text,
    subtitle = subtitle_text,
    x = "Data",
    caption = caption_text
  ) +
  theme(
        plot.title = ggtext::element_markdown(size = 25, color = "gray40", family = font, face = "bold",   hjust = 0),
        plot.subtitle = ggtext::element_markdown(size = 15, color = "gray40", family = font, face = "italic",   hjust = 0),        
        plot.caption = ggtext::element_markdown(size = 8, color = txt_col, family = font, hjust = 0, margin = margin(10,0,0,0), lineheight = 1.2),
        panel.background = element_rect(fill = "white", color = "grey90"),
        plot.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey90"),
        legend.background = element_blank(),
        legend.position = c(0.7, 0.8),
        legend.key = element_rect(fill = "grey95", color = "grey95"),
        legend.text = element_text(color = "grey40", size = 12),
        legend.title = element_text(face = "bold", color = "grey40"),
        axis.title.x = ggtext::element_markdown(face = "bold", family = font,size = 15, hjust = 0, color = "gray50"), # nolint,
        axis.title.y = element_blank(),
        axis.text.y = ggtext::element_markdown(face = "bold", family = font2,size = 8, hjust = 0, color = "gray50"), # nolint,
        axis.text.x = ggtext::element_markdown(
          face = "bold", family = font2 ,size = 8, color = "gray50", angle = 90, hjust = 1) # nolint
  )
agio
```

```{r}
ggsave(".vscode/Graph index/AgioBezerro.png", plot = agio, width = 16, height = 10, dpi = 300)
```