---
title: ""
description: ""
author script: 
  - name: "Ítalo Marques-Monteiro"
    github: https://github.com/italomarquesmonteiro
    kaggle: https://www.kaggle.com/talomarquesmonteiro
    linkedin: linkedin.com/in/ítalo-monteiro-0b2516144
    lattes: http://lattes.cnpq.br/7174985368517137
    orcid_id: https://orcid.org/0000-0003-4367-1034
    affiliation: Smart Data
        
date: "2024-01-06"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
praca_rs <- readr::read_csv(
    "c:/Users/italo/OneDrive/Área de Trabalho/GitHub/NESPro/.vscode/Dataset/GadoGordo.csv" # nolint
  ) |>
  dplyr::filter(preco == "Médio") |>
  dplyr::select(!c(pv_macho, pv_femea)) |>
  dplyr::mutate(
    pc_macho = pc_macho * 15,
    pc_femea = pc_femea * 15
  )

praca_sp <- readr::read_csv(
  "c:/Users/italo/OneDrive/Área de Trabalho/GitHub/Cepea-Esalq/.vscode/Dataset cepea/CepeaBoiGordo.csv" # nolint
  ) |>
  dplyr::select(data, a_vista_r)


#vaca_sp <- readxl::read_xlsx("c:/Users/italo/OneDrive/Área de Trabalho/VsCode/agrolink/VacaGordaSP.xlsx") |> # nolint
#  tidyr::separate(data, into = c("data", "hora"), " ") |>
#  dplyr::select(!hora) |>
#  dplyr::mutate(data = lubridate::ymd(data))
```


```{r}
base_gado_gordo <- praca_rs |>
  dplyr::inner_join(praca_sp) |>
  #dplyr::inner_join(vaca_sp) |>
  tidyr::pivot_longer(
    !c(data, preco),
      names_to = "categoria",
        values_to = "arroba"
  ) |>
  dplyr::mutate(
    categoria = case_when(
      categoria == "pc_macho" ~ "Boi Gordo-RS",
      categoria == "pc_femea" ~ "Vaca Gorda-RS",
      categoria == "a_vista_r" ~ "Boi Gordo-SP",
      #categoria == "vaca_groda_sp" ~ "Vaca Gorda-SP"

    )
  ) |>
  dplyr::select(!preco) |>
  dplyr::filter(data >= "2020-10-27")
```


```{r}
label_title <- "Comportamento da arroba do boi gordo nas praças de São Paulo e Rio Grande do Sul" # nolint
label_caption <- "Nota:  Valor por arroba de 15 kg. Os valores do preço da arroba são referentes as mesmas datas de divulgação em ambas as praças  \nDados do boi gordo RS: Núcleo de Estudos em Sistemas de Produção de Bovinos de Corte e Cadeia Produtiva (NESPro) \n Dados do boi gordo SP: Centro de Estudos Avançados em Economia Aplicada (Cepea) \nPlot: @italo.m.m" # nolint
```

```{r}
bg <- "white"
txt_col <- "black"

font <- "Josefin Sans"
font2 <- "Open Sans"

# Use the font_add_google() function to load fonts from the web
sysfonts::font_add_google(family = font, font, db_cache = FALSE)
sysfonts::font_add_google(family = font2, font2, db_cache = FALSE)

sysfonts::font_add(family = "Font Awesome 6 Brands", regular = "C:/Users/italo/AppData/Local/Microsoft/Windows/Fonts/Font Awesome 6 Brands-Regular-400.otf") # nolint

theme_set(theme_minimal(base_family = font2, base_size = 3))

showtext::showtext_opts(dpi = 300)
showtext::showtext_auto(enable = TRUE)


github_icon <- "&#xf09b"
linkedin_icon <- "&#xf0e1"
x_icon <- "&#xf099"
instagram_icon <- "&#xf16d"
github_username <- "italomarquesmonteiro"
linkedin_username <- "italomarquesmonteiro"
x_username <- "italommonteiro"
instagram_username <- "italo.m.m"

colors <- "gray40"
title_text <- glue::glue('Comportamento da arroba do boi gordo nas praças de São Paulo e Rio Grande do Sul') # nolint
subtitle_text <- glue::glue("")
caption_text <- glue::glue(
  "**Dados:** Núcleo de Estudos em Sistemas de Produção de Bovinos de Corte e Cadeia Produtiva (NESPro) e Centro de Estudos Avançados em Economia Aplicada (Cepea-Esalq)<br>", # nolint
  "**Nota:** Nota:  Valor por arroba de 15 kg. Os valores do preço da arroba são referentes as mesmas datas de divulgação em ambas as praças<br>",
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: black;'>{github_icon};</span> 
  <span style='color: black'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: dodgerblue4;'>{linkedin_icon};</span> 
  <span style='color: black'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: black'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: red;'>{instagram_icon};</span>
  <span style='color: black'>{instagram_username}</span>"
)
```


```{r}
plot_gado_gordo <- base_gado_gordo |>
  dplyr::filter(data > "2020-10-27", categoria %in% c("Boi Gordo-SP", "Boi Gordo-RS")) |> # nolint
  ggplot2::ggplot(
    mapping = aes(
      x = data,
        y = arroba,
          color = categoria
    )
  ) +
  geom_line(na.rm = TRUE) +
  geom_smooth(method = "gam", alpha = 0.18, na.rm = TRUE) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  scale_y_continuous(breaks = seq(100, 350, 15), labels = scales::dollar_format(
    prefix = "", suffix = " R$/@")) +
  scale_color_manual(values = c("steelblue", "grey70")) +
  labs(
    title = title_text,
      x = "Data",
      caption = caption_text,
      color = ""
  ) +
  theme(
        plot.title = ggtext::element_markdown(face = "bold", family = font, size = 25, hjust = 0, color = "gray40",), # nolint
        plot.caption = ggtext::element_markdown(family = font, hjust = 0, margin = margin(10,0,0,0), size = 8, color = txt_col, lineheight = 1.2), # nolint
        panel.background = element_rect(fill = "white", color = "grey90"),
        plot.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey90"),
        legend.background = element_blank(),
        legend.position = c(0.7, 0.8),
        legend.key = element_rect(fill = "grey95", color = "grey95"),
        legend.text = element_text(color = "grey40", size = 12),
        legend.title = element_text(face = "bold", color = "grey40", size = 12),
        axis.title.x = ggtext::element_markdown(face = "bold", family = font,size = 15, hjust = 0, color = "gray50"), # nolint,
        axis.title.y = element_blank(),
        axis.text.y = ggtext::element_markdown(face = "bold", family = font2,size = 8, hjust = 0, color = "gray50"), # nolint,
        axis.text.x = ggtext::element_markdown(
          face = "bold", family = font2 ,size = 8, color = "gray50", angle=60, hjust=1) # nolint
  )
plot_gado_gordo
```


```{r}
ggsave(".vscode/Graph index/BoiGordo-RS-SP.png",
  plot = plot_gado_gordo,
    width = 15,
      height = 9,
        dpi = 500
  )
```

