---
title: "Relação de troca do boi gordo"
description: "A relação de troca do boi gordo é um indicador crucial na pecuária, destacando a proporção entre o preço de venda do boi gordo e o custo de aquisição de outros produtos, como gado de reposição. Essa métrica não apenas sinaliza a viabilidade econômica da transição entre fases do ciclo pecuário, mas também indica a capacidade do pecuarista em adquirir animais de reposição ou investir em outros insumos essenciais para a produção. Uma relação de troca favorável sugere uma maior capacidade de compra, enquanto uma relação desfavorável pode impactar as decisões estratégicas do pecuarista em termos de retenção, venda ou investimento no seu rebanho."
author script: 
  - name: "Ítalo Marques-Monteiro"
    github: https://github.com/italomarquesmonteiro
    kaggle: https://www.kaggle.com/talomarquesmonteiro
    linkedin: linkedin.com/in/italomarquesmonteiro
    medium: https://medium.com/@italomarquesmonteiro
    lattes: http://lattes.cnpq.br/7174985368517137
    orcid_id: https://orcid.org/0000-0003-4367-1034
    affiliation: Smart Data
        
date: "2024-01-26"
output: html_document
---

```{r Library}
library(tidyverse)
```

```{r Datasets}
bezerro_cepea <- readr::read_csv("c:\\Users\\italo\\Desktop\\GitHub\\Cepea-Esalq\\.vscode\\Dataset cepea\\CalfPrice.csv") |> # nolint "c:/Users/italo/Desktop/GitHub/NESPro/.vscode/Dataset/GadoGordo.csv"
  dplyr::select(data, preco_bezerro = a_vista_r)
boi_cepea <- readr::read_csv("c:\\Users\\italo\\Desktop\\GitHub\\Cepea-Esalq\\.vscode\\Dataset cepea\\CepeaBoiGordo.csv" ) |> # nolint 
  dplyr::select(data, arroba_boi = a_vista_r)

bezerro_nespro <- readr::read_csv("c:\\Users\\italo\\Desktop\\GitHub\\NESPro\\.vscode\\Dataset\\GadoReposição.csv") |> 
  dplyr::filter(preco == "Médio") |>
  dplyr::select(data, kg_bezerro = terneiro_6_12_m)
boi_nespro <- readr::read_csv("c:\\Users\\italo\\Desktop\\GitHub\\NESPro\\.vscode\\Dataset\\GadoGordo.csv") |> # nolint 
  dplyr::filter(preco == "Médio") |>
  dplyr::select(data, kg_boi = pv_macho)
#unique(boi_nespro$preco)
```

A fórmula para usada calcular a relação de troca da @ boi gordo é:
  **Relação de troca** = *Preço da @ boi grodo / Preço do bezerro*
```{r Joining}
rt_cepea <- boi_cepea |>
  dplyr::inner_join(bezerro_cepea) |>
  dplyr::mutate(ano = year(data), mes = month(data), .before = data) |>
  print(n = 30)
rt_nespro <- boi_nespro |>
  dplyr::inner_join(bezerro_nespro) |>
  dplyr::mutate(ano = year(data), mes = month(data), .before = data) |>
  print(n = 30)
```

```{r summarise}
relacao_troca_cepea <- rt_cepea |>
  dplyr::mutate(rt = preco_bezerro / arroba_boi) |>
  dplyr::group_by(ano, mes) |>
  dplyr::summarise(rt_medio = mean(rt, na.rm = TRUE)) |>
  dplyr::mutate(data = lubridate::ymd(paste(ano, mes, "01")), .before = rt_medio) 

relacao_troca_nespro <- rt_nespro |>
  dplyr::mutate(rt = kg_bezerro / kg_boi) |>
  dplyr::group_by(ano, mes) |>
  dplyr::summarise(rt_medio = mean(rt, na.rm = TRUE)) |>
  dplyr::mutate(data = lubridate::ymd(paste(ano, mes, "01")), .before = rt_medio) 
```

```{r period average}
relacao_troca_cepea |> #arrange(desc(rt_medio))
  dplyr::select(rt_medio) |>
  dplyr::mutate(media_periodo = mean(rt_medio))

relacao_troca_nespro |> #arrange(desc(rt_medio))
  dplyr::select(rt_medio) |>
  dplyr::mutate(media_periodo = mean(rt_medio, na.rm = TRUE))
```


```{r}
bg <- "white"
txt_col <- "black"
font <- "Josefin Sans"
font2 <- "Open Sans"
sysfonts::font_add_google(family = font, font, db_cache = FALSE)
sysfonts::font_add_google(family = font2, font2, db_cache = FALSE)
sysfonts::font_add(family = "Font Awesome 6 Brands", regular = "C:/Users/italo/AppData/Local/Microsoft/Windows/Fonts/Font Awesome 6 Brands-Regular-400.otf") # nolint
#theme_set(theme_minimal(base_family = font2, base_size = 3))
showtext::showtext_opts(dpi = 300)
showtext::showtext_auto(enable = TRUE)
github_icon <- "&#xf09b"
linkedin_icon <- "&#xf0e1"
x_icon <- "&#xf099"
instagram_icon <- "&#xf16d"
github_username <- "italomarquesmonteiro"
linkedin_username <- "italomarquesmonteiro"
x_username <- "italommonteiro"
instagram_username <- "italo.m.m"
colors <- "gray40"
title_text <- glue::glue("Relação de Troca")
subtitle_text <- glue::glue("Quantidade de arrobas (@) de boi gordo<br>necessária para adquirir um bezerro(cabeça).")
caption_text <- glue::glue(
  "**Nota:** A linha horizontal tracejada representa o valor médio do período. As barras escuras representam os valores mínimo e máximo dentro do período.<br>",
  "**Dados:** Centro de Estudos Avançados em Economia Aplicada (Cepea-Esalq)<br>", # nolint
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: black;'>{github_icon};</span> 
  <span style='color: black'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: dodgerblue4;'>{linkedin_icon};</span> 
  <span style='color: black'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: black'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: red;'>{instagram_icon};</span>
  <span style='color: black'>{instagram_username}</span>"
)
title_text1 <- glue::glue("Relação de Troca")
subtitle_text1 <- glue::glue("Quantos quilos (kg) de boi gordo são necessários para comprar<br>um quilo de bezerro na faixa etária de 6 a 12 meses.")
caption_text1 <- glue::glue(
  "**Nota:** A linha horizontal tracejada representa o valor médio do período. As barras escuras representam os valores mínimo e máximo dentro do período.<br>",
  "**Dados:** Núcleo de Estudos em Sistemas de Produção de Bovinos de Corte e Cadeia Produtiva (NESPro-UFRGS)<br>", # nolint
  "**Plot:** Ítalo Marques-Monteiro <br><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: black;'>{github_icon};</span> 
  <span style='color: black'>{github_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: dodgerblue4;'>{linkedin_icon};</span> 
  <span style='color: black'>{linkedin_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: steelblue;'>{x_icon};</span>
  <span style='color: black'>{x_username}</span><br>",
  "<span style='font-family:\"Font Awesome 6 Brands\"; color: red;'>{instagram_icon};</span>
  <span style='color: black'>{instagram_username}</span>"
)
```

```{r}
relacao_troca_cepea |>
  dplyr::arrange(rt_medio)
  #dplyr::arrange(desc(rt_medio))
  #dplyr::arrange(desc(data))
```
  
  
```{r plot} 
plot_rt_nespro <- relacao_troca_nespro |>
  ggplot(aes(x = data, y = rt_medio) ) +
  geom_col(aes(fill = ifelse(data == max(data), "last",ifelse(data %in% c("2022-12-01", "2021-04-01"),"high", "default")))) +
  #geom_col(aes(fill = ifelse(data == max(data), "last",ifelse(data %in% c("2021-10-01", "2004-11-01"),"high", "default")))) +
  scale_fill_manual(values = c("min" = "grey50", "max" = "grey50", "last" = "goldenrod1", "default" = "grey80")) +
  #scale_fill_manual(values = c(high = "grey50", default = "grey80", last = "goldenrod1", color = "black")) +
  guides(fill = FALSE) +
  #geom_hline(yintercept = 6.61, lty = 3) +
  geom_hline(yintercept = 1.29, lty = 3) +
  #scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %Y") +
  #scale_y_continuous(breaks = seq(0, 12, 1), labels = scales::dollar_format(prefix = "", suffix = " @")) +
  scale_y_continuous(breaks = seq(0, 2, 0.1), labels = scales::dollar_format(prefix = "", suffix = " kg")) +
  labs(
    title = title_text1,
    x = "Data",
    subtitle = subtitle_text1,
    caption = caption_text1
  ) +
  theme(
        plot.title = ggtext::element_markdown(face = "bold", family = font, size = 25, hjust = 0, color = "gray40",), 
        plot.subtitle = ggtext::element_markdown(face = "bold", family = font, size = 15, hjust = 0, color = "gray40",),       
        plot.caption = ggtext::element_markdown(family = font, hjust = 0, margin = margin(10,0,0,0), size = 8, color = txt_col, lineheight = 1.2), 
        panel.background = element_rect(fill = "white", color = "grey90"),
        plot.background = element_rect(fill = "white"),
        panel.grid = element_line(color = "grey90"),
        legend.background = element_blank(),
        legend.position = c(0.7, 0.8),
        legend.key = element_rect(fill = "grey95", color = "grey95"),
        legend.text = element_text(color = "grey40", size = 12),
        legend.title = element_text(face = "bold", color = "grey40"),
        axis.title.x = ggtext::element_markdown(face = "bold", family = font,size = 15, hjust = 0, color = "gray50"),
        axis.title.y = element_blank(),
        axis.text.y = ggtext::element_markdown(face = "bold", family = font2,size = 8, hjust = 0, color = "gray50"), 
        axis.text.x = ggtext::element_markdown(
          face = "bold", family = font2 ,size = 8, color = "gray50", angle = 90, hjust = 1) 
  )
plot_rt_nespro
```

```{r}
ggsave(".vscode/Graph index/RT-Nespro.png", plot = plot_rt_nespro, dpi = 300)
```